server:
  port: 8081

redis:
  config:
    multiple:
      - name: default
        database: 0
        timeout: 6000ms
        cluster:
          nodes: redis-sport-dev.gz1rrk.clustercfg.cnw1.cache.amazonaws.com.cn:6379
        jedis:
          pool:
            max-active: 100  #连接池最大连接数（使用负值表示没有限制）
            max-idle: 10   # 连接池中的最大空闲连接
            min-idle: 10    # 连接池中的最小空闲连接
            max-wait: 1000  # 连接池最大阻塞等待时间（使用负值表示没有限制）